# Generated by Django 4.0.3 on 2022-04-19 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import notifications.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="emailnotification",
            managers=[
                ("objects", notifications.models.NotificationEmailManager()),
            ],
        ),
        migrations.AlterField(
            model_name="basicnotification",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="%(app_label)s_%(class)s_sending_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="basicnotification",
            name="recipients",
            field=models.ManyToManyField(
                related_name="%(app_label)s_%(class)s_receiving_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="emailnotification",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="%(app_label)s_%(class)s_sending_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="emailnotification",
            name="recipients",
            field=models.ManyToManyField(
                related_name="%(app_label)s_%(class)s_receiving_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pushnotification",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="%(app_label)s_%(class)s_sending_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pushnotification",
            name="recipients",
            field=models.ManyToManyField(
                related_name="%(app_label)s_%(class)s_receiving_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
