# Generated by Django 4.0.3 on 2022-04-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_emailnotification_managers_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="basicnotification",
            old_name="from_user",
            new_name="sender",
        ),
        migrations.RenameField(
            model_name="emailnotification",
            old_name="from_user",
            new_name="sender",
        ),
        migrations.RenameField(
            model_name="pushnotification",
            old_name="from_user",
            new_name="sender",
        ),
    ]
