# Generated by Django 4.0.3 on 2022-04-19 15:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0003_rename_from_user_basicnotification_sender_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BasicNotification",
            new_name="NotificationBasic",
        ),
        migrations.RenameModel(
            old_name="EmailNotification",
            new_name="NotificationEmail",
        ),
        migrations.RenameModel(
            old_name="EmailTemplate",
            new_name="NotificationEmailTemplate",
        ),
        migrations.RenameModel(
            old_name="PushNotification",
            new_name="NotificationPush",
        ),
    ]
