# Generated by Django 4.0.3 on 2022-04-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_rename_basicnotification_notificationbasic_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificationbasic",
            name="recipients",
        ),
        migrations.AddField(
            model_name="notificationbasic",
            name="recipients",
            field=models.CharField(
                default="danielnazarian@outlook.com", max_length=900
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notificationbasic",
            name="sender",
            field=models.CharField(max_length=300),
        ),
        migrations.RemoveField(
            model_name="notificationemail",
            name="recipients",
        ),
        migrations.AddField(
            model_name="notificationemail",
            name="recipients",
            field=models.CharField(
                default="danielnazarian@outlook.com", max_length=900
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notificationemail",
            name="sender",
            field=models.CharField(max_length=300),
        ),
        migrations.RemoveField(
            model_name="notificationpush",
            name="recipients",
        ),
        migrations.AddField(
            model_name="notificationpush",
            name="recipients",
            field=models.CharField(
                default="danielnazarian@outlook.com", max_length=900
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notificationpush",
            name="sender",
            field=models.CharField(max_length=300),
        ),
    ]
