# Generated by Django 4.0.3 on 2022-05-13 23:33

import django.db.models.deletion
from django.db import migrations, models

import notifications.models.email


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_remove_notificationbasic_recipients_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="notificationemailtemplate",
            managers=[
                (
                    "objects",
                    notifications.models.email.NotificationEmailTemplateManager(),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="notificationbasic",
            name="sender",
            field=models.CharField(
                help_text="This should be the users email.", max_length=300
            ),
        ),
        migrations.AlterField(
            model_name="notificationemail",
            name="sender",
            field=models.CharField(
                help_text="This should be the users email.", max_length=300
            ),
        ),
        migrations.AlterField(
            model_name="notificationemail",
            name="template",
            field=models.ForeignKey(
                default=notifications.models.email.get_default_template,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="template",
                to="notifications.notificationemailtemplate",
            ),
        ),
        migrations.AlterField(
            model_name="notificationpush",
            name="sender",
            field=models.CharField(
                help_text="This should be the users email.", max_length=300
            ),
        ),
    ]
