name: Lint

on:
  push

jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run black
        uses: psf/black@stable

      - name: Run flake8
        run: pip install flake8==4.0.1 && flake8 .